services:
  postgres_db_test:
    image: postgres:16
    container_name: crm_db_test
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES_DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d srm_db" ]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: unless-stopped

  rabbitmq_test:
    image: rabbitmq:3-management-alpine
    container_name: crm_rabbitmq_test
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
